name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          cd simulatortofmu/SimulatorToFMU/simulatortofmu/bin
          $CONDA/bin/conda update -n base -c defaults conda
          $CONDA/bin/conda install libxml2
          $CONDA/bin/conda install -c conda-forge pyfmi
          cd ../../simulatortofmu/bin/
          python runUnitTest.py
          #python -m pip install --upgrade pip
          #pip install flake8 pytest
          #if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

