name: Running Tests for SimulatorToFMU

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge
      - name: Install Python dependencies
        run: |
          $CONDA/bin/conda install -c anaconda jinja2
          $CONDA/bin/conda install -c conda-forge pyfmi
      - name: Install OpenModelica
        uses: THM-MoTE/setup-openmodelica@v1  
        with:
          version: 1.19.2 
      - name: Running the tests
        run: |
          cd simulatortofmu/bin/
          python runUnitTest.py

       
